### ISSUE TITLE
the "progress dialog" will not auto rotation when the "orientation" happen (real device)

### ISSUE THREAD

**Issue by bau720123** [leecrossley/cordova-plugin-progress#2]
hi @leecrossley 
awesome plugin
the "progress dialog" will not auto rotation when the "orientation" happen (real device)

if my device start at "landscape" mode，run your code，but the "progress dialog" still show "portrait" mode

**Comment by leecrossley** [comment]
This works OK for me, even switching orientation. Please provide a full sample app with instructions and I will reopen.

**Comment by leecrossley** [comment]
Also, please check your app actually allows landscape.

**Comment by bau720123** [comment]
hi @leecrossley 
so strange...
my app allows landscape indeed
here is my screenshot and code

[portrait]
![portrait](https://cloud.githubusercontent.com/assets/5110085/9704415/7a36df4c-54d8-11e5-94a5-04bd00857e6d.JPG)

[landscape]
![landscape](https://cloud.githubusercontent.com/assets/5110085/9704414/7a3522b0-54d8-11e5-9c55-1d343e286951.JPG)

```
progress.show(null, null, {"text": "the word"});
```

**Comment by leecrossley** [comment]
sorry - I have not tested on iPad

**Comment by leecrossley** [comment]
I have tested on iPad and the plugin itself works fine, exactly the same as it does on iPhone even with orientation change. This is with the default cordova project.

**Comment by bau720123** [comment]
hi @leecrossley 
thanks for your reply
I trust you totally

well..just want to ask
what is your ios version ?
I am using 8.4.1 (12H321)

cordova version ?
when in PGB (build.phonegap.com)，I am using 5.1.1

Can you guess what problem maybe cause this situation just like my screenshot ? (maybe I can ask the PGB team)

**Comment by leecrossley** [comment]
Tested using iPad Air and iPhone 6 (latest iOS), via the Cordova CLI and Cordova v5.2.0 (have previously tested with 5.1.1). I think it's unlikely the PGB team will help with custom plugins. Can you confirm you are not using any other plugins (e.g. cordova-plugin-device-orientation) that may be interfering?

**Comment by bau720123** [comment]
hi @leecrossley 
just like you said
I use "cordova-plugin-device-orientation" 1.0.1 version indeed
https://www.npmjs.com/package/cordova-plugin-device-orientation
but "cordova-plugin-device-orientation" is a official plugin
is it will "interfering" yours ? how could ? why ?
or you want me do a test first (remove "cordova-plugin-device-orientation" and try again yours) ?

**Comment by leecrossley** [comment]
It's just a suggestion based on my past experience but I don't know much abut the device orientation plugin. Unfortunately I'm unable to help out further, as your issue isn't something that can be fixed by this plugin.

**Comment by bau720123** [comment]
all right
thanks @leecrossley 
I will try if something "interfering"
if any clues that I found it，feedback again
thanks

**Comment by bau720123** [comment]
hi @leecrossley 
Unfortunately...
still "interfering" only in landscape mode
you can download my full project
www.littlebau.com/phonegap_build_5.2.0.zip
only 31K

you can see my config.xml is super easy (I delete almost 99% plugins)
if you have ever use PGB，you can directly upload this zip file to your own project and redownload the ipa file from PGB
install it through itunes or other tools you like
open the app and click the "mytest" in landscape mode and you will see my scene

**Comment by bau720123** [comment]
hi @leecrossley 
is my zip file can help you something ?

**Comment by bau720123** [comment]
hi @leecrossley 
is the zip file can do some track ?

**Comment by bau720123** [comment]
hi @leecrossley 
could you give me yours info.plist key and value ?

```
<key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
```

so...let me check what the difference between by yours and me

**Comment by bau720123** [comment]
hi @leecrossley 
problem solved
anyway，thanks
