### ISSUE TITLE
My app freeze on iOS9

### ISSUE THREAD

**Issue by hirbod** [leecrossley/cordova-plugin-progress#3]
Hi,

just tried the plugin. I can trigger a progress, but as soon as I show the spinner, app will freeze. Can't hide or update. But I have no crash in console. It just stop working and I can't do anything.

iOS 9, Xcode 7, tested on simulator

**Comment by leecrossley** [comment]
Hi,

Unfortunately, this is an issue with your implementation - I have tested on iOS 9 with Xcode 7 (the only issue is you must set Bitcode to NO at the moment, but this is not your issue).

All I can suggest is that you strip your app right back and do something simple like (after device ready):

``` js
// show
progress.show("Loading...");

setTimeout(function () {
    // hide
    progress.hide();
}, 3000);
```
